### ISSUE TITLE
Misleading debug log in ClientExampleScript

### ISSUE THREAD

**Issue by MarcosAlfonso** [PlayFab/PlayFabGameServer#1]
In the Unity Client example project "PlayFabGameServerClientExample", [line 156](https://github.com/PlayFab/PlayFabGameServer/blob/master/PlayFabGameServerClientExample/Assets/GameServerClientExample/Scripts/ClientExampleScript.cs#L156) of ClientExampleScript.cs has a misleading Debug.Log. It currently states that once connected "Network Client Authenticated, You have 30 seconds to Authenticate or you get booted by the server." 

I believe this should say "Network Client _**Connected**_, You have 30 seconds to Authenticate or you get booted by the server."

**Comment by pgilmorepf** [comment]
Your suggestion has been accepted.  It should be published to the repo in the next week or so.

Thanks for your submission.
