### ISSUE TITLE
Is there any way to get the same but without IoC?

### ISSUE THREAD

**Issue by artfabrique** [PlayFab/PlayFabGameServer#19]
Hi there! Do you plan to do the same but without StrangeIoC?

**Comment by pgilmorepf** [comment]
The StrangeIoC wrappers are "extra".  They're not needed or required, they just add another syntax for using PlayFab if you're familiar with StrangeIoC. You don't have to use them.
Also, we might be removing some StrangeIoC wrappers that aren't specifically used in the example.
