### ISSUE TITLE
Default value for IsCustomLogFile appears to prevent creating log file

### ISSUE THREAD

**Issue by MarcosAlfonso** [PlayFab/PlayFabGameServer#2]
It appears that the if statement of [line 43](https://github.com/PlayFab/PlayFabGameServer/blob/master/GameServerSource/Assets/Contexts/PlayFabServer/Commands/LogCommands.cs#L43), and the fact that IsCustomLogFile initializes to false by default means no logs are saved to the LogFilePath on a fresh custom server

Unless I am mistaken this is not the intended functionality based off that variable name and it makes it impossible to debug server builds uploaded to the game manager, which is particularly unclear when starting out.

**Comment by MarcoWilliamsPF** [comment]
-logFile <log_file_path>   is the proper logfile path which is in build params in the Game Manager.  Unity Servers log differently than normal game servers written in pure C#
