### ISSUE TITLE
Lost Scripts

### ISSUE THREAD

**Issue by cipriantk** [PlayFab/PlayFabGameServer#25]
The project seems to only contain the playfab sdk ...

![image](https://user-images.githubusercontent.com/22867925/45916028-abeac980-be67-11e8-9381-350c97460fba.png)

**Comment by Myfreedom614** [comment]
We can repro this issue, the customer also report it in forum: https://community.playfab.com/questions/23357/error-with-custom-game-server-github.html

**Comment by pgilmorepf** [comment]
Thanks for reporting this.
We've rolled back the repo to a checkin before this error, and future publishes should contain the files.
Apologies for the confusion.
